AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
 sam-app


 Sample SAM Template for sam-app


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
 Function:
   Timeout: 3


   # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
   LoggingConfig:
     LogFormat: JSON
Resources:
 ShortenUrlFunction:
   Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
   Properties:
     CodeUri: shorten_service/
     Handler: app.lambda_handler
     Runtime: python3.13
     Architectures:
     - x86_64
     Environment:
       Variables:
         URL_LOOKUP_TABLE_NAME_DYNAMODB: !Ref UrlTable
     Policies:
       - DynamoDBCrudPolicy:
          TableName: !Ref UrlTable
     Events:
       ShortenUrl:
         Type: Api
         Properties:
           Path: /shorten
           Method: post
 UrlTable:
   Type: AWS::Serverless::SimpleTable
   Properties:
     PrimaryKey: # <-- Correct indentation
       Name: id
       Type: String


Outputs:
 # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
 # Find out more about other implicit resources you can reference within SAM
 # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
 ShortenUrlApi:
      Description: API Gateway endpoint URL for Prod stage for Shorten URL function
      Value: !Sub "https://{ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/shorten/"
ShortenUrlFunction:
    Description: Shorten URL Lambda Function ARN
    Value: !GetAtt ShortenUrlFunction.Arn
ShortenUrlFunctionIamRole:
    Description: Implicit IAM Role created for Shorten URL function
    Value: !GetAtt ShortenUrlFunctionRole.Arn
   